### ISSUE TITLE
small but important typo in the docs

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-q-card#3]
been staring myself blind why my first attempts to use this custom card kept giving me the red card of an unknown card type qcard...

need to add 'custom:' in front of the q-card:

```
views:
  - title: One view
    cards:
      - type: q-card
        card: card1
  - title: Another view
    cards:
      - type: q-card
        card: card1
```

should be:

```
views:
  - title: One view
    cards:
      - type: custom:q-card
        card: card1
  - title: Another view
    cards:
      - type: custom:q-card
        card: card1
```

while I am it, shouldn't the reference to the resources be changed?
you still show:
```
title: My awesome lovelace configuration
resources:
  - url: /local/q-card.js
    type: module
q_cards:
```
while the `resources:` now are listed under the `lovelace:` key in configuration.yaml?
